name: Build

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [ 2.11, 2.12 ]
        spark: [ 2, 3 ]
        exclude:
          - scala: 2.11
            spark: 3
    name: Scala ${{ matrix.scala }}, Spark ${{ matrix.spark }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.scala }}-${{ matrix.spark }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.scala }}-${{ matrix.spark }}-
      - name: Install Maven 3.8.4
        run: mvn -N wrapper:wrapper -Dmaven=3.8.4
      - name: License check
        run: ./mvnw clean validate --no-transfer-progress -Plicense-check,spark-2,spark-3,scala-2.12
      - name: Switch scala version
        run: ./mvnw scala-cross-build:change-version --no-transfer-progress -Pscala-${{ matrix.scala }},spark-${{ matrix.spark }}
      - name: Build and run tests
        run: ./mvnw clean verify --no-transfer-progress -Pscala-${{ matrix.scala }},spark-${{ matrix.spark }},all-tests
