name: Build

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [ 2.11, 2.12 ]
        spark: [ 2, 3 ]
        exclude:
          - scala: 2.11
            spark: 3
    name: Scala ${{ matrix.scala }}, Spark ${{ matrix.spark }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.scala }}-${{ matrix.spark }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.scala }}-${{ matrix.spark }}-
      - name: Switch scala version
        run: mvn scala-cross-build:change-version -Pscala-${{ matrix.scala }}
      - name: Build and run tests
        run: mvn clean test -Pscala-${{ matrix.scala }},spark-${{ matrix.spark }},all-tests
